language: c

addons:
    apt:
        packages:
            - clang-3.6
            - gcc-5
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test

os:
    - linux
    - osx

compiler:
    - clang
    - clang-3.6
    - gcc
    - gcc-5


matrix:
    exclude:
        - os: osx
          compiler: clang-3.6
        - os: osx
          compiler: gcc-5

script:
    - make hello

